<?php
declare(strict_types=1);

namespace Laventure\Component\Routing\Enums;

/**
 * HttpMethod
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package  Laventure\Component\Routing\Enums
 *
 * Generated By PHPStorm 20.12.2023
*/
class HttpMethod
{
    const GET     = 'GET';
    const HEAD    = 'HEAD';
    const POST    = 'POST';
    const PUT     = 'PUT';
    const PATCH   = 'PATCH';
    const DELETE  = 'DELETE';
}