<?php
declare(strict_types=1);

namespace PHPUnitTest\Component\Routing\Controllers;

/**
 * HomeController
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package  PHPUnitTest\Component\Routing\Controllers
 *
 * Generated By PHPStorm 21.12.2023
 */
class HomeController
{
     public function index()
     {
         return __METHOD__;
     }
}