<?php

declare(strict_types=1);

namespace PHPUnitTest\Component\Routing\Middlewares;

/**
 * GuestMiddleware
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package  PHPUnitTest\Component\Routing\Middlewares
 *
 * Generated By PHPStorm 20.12.2023
 */
class GuestMiddleware
{
    public function __invoke($request, callable $next)
    {
        // TODO: Implement __invoke() method.
    }
}
