<?php
declare(strict_types=1);

namespace Laventure\Component\Routing;

use Laventure\Component\Routing\Route\Route;

/**
 * RouteCollection
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package  Laventure\Component\Routing
 *
 * Generated By PHPStorm 20.12.2023
 */
class RouteCollection
{

    /**
     * @var Route[]
    */
    protected ?array $routes = [];




    /**
     * @var Route[]
    */
    protected ?array $methods = [];




    /**
     * @var Route[]
    */
    protected ?array $controllers = [];






    /**
     * @var Route[]
    */
    protected ?array $namedRoutes = [];





    /**
     * @param Route $route
     *
     * @return Route
    */
    public function addRoute(Route $route): Route
    {
        $this->methods[$route->getMethod()][] = $route;

        if ($controller = $route->getController()) {
            $this->controllers[$controller][] = $route;
        }

        if($name = $route->getName()) {
            $this->namedRoutes[$name] = $route;
        }

        return $this->routes[] = $route;
    }






    /**
     * @param string $name
     *
     * @param Route $route
     *
     * @return Route
    */
    public function add(string $name, Route $route): Route
    {
        $this->namedRoutes[$name] = $route;

        return $this->addRoute($route);
    }




    /**
     * @param string $name
     *
     * @return bool
    */
    public function hasRoute(string $name): bool
    {
        return array_key_exists($name, $this->namedRoutes);
    }




    /**
     * @param string $name
     *
     * @return Route|null
    */
    public function getRoute(string $name): ?Route
    {
        return $this->namedRoutes[$name] ?? null;
    }





    /**
     * @return Route[]
    */
    public function getNamedRoutes(): array
    {
        return $this->namedRoutes;
    }






    /**
     * @param Route[] $routes
     *
     * @return $this
    */
    public function addRoutes(array $routes): static
    {
        foreach ($routes as $route) {
            $this->addRoute($route);
        }

        return $this;
    }




    /**
     * @return Route[]
    */
    public function getRoutes(): array
    {
        return $this->routes;
    }
}
