<?php

declare(strict_types=1);

namespace Laventure\Component\Routing;

use Laventure\Component\Routing\Route\RouteInterface;

/**
 * RouterInterface
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package  Laventure\Component\Routing
 *
 * Generated By PHPStorm 20.12.2023
 */
interface RouterInterface
{
    /**
     * @param string $methods
     *
     * @param string $path
     *
     * @param mixed $action
     *
     * @param string|null $name
     * @return RouteInterface
    */
    public function map(string $methods, string $path, mixed $action, string $name = null): RouteInterface;




    /**
     * @param string $path
     *
     * @param mixed $action
     *
     * @param string|null $name
     *
     * @return RouteInterface
    */
    public function get(string $path, mixed $action, string $name = null): RouteInterface;






    /**
     * @param string $path
     * @param mixed $action
     * @param string|null $name
     * @return RouteInterface
    */
    public function post(string $path, mixed $action, string $name = null): RouteInterface;








    /**
     * @param string $path
     * @param mixed $action
     * @param string|null $name
     * @return RouteInterface
    */
    public function put(string $path, mixed $action, string $name = null): RouteInterface;





    /**
     * @param string $path
     * @param mixed $action
     * @param string|null $name
     * @return RouteInterface
    */
    public function delete(string $path, mixed $action, string $name = null): RouteInterface;






    /**
     * Determine if the current request match route
     *
     * @param string $method
     *
     * @param string $path
     *
     * @return RouteInterface|false
    */
    public function match(string $method, string $path): RouteInterface|false;






    /**
     * Generate URI
     *
     * @param string $name
     *
     * @param array $parameters
     *
     * @return string|null
    */
    public function generate(string $name, array $parameters = []): ?string;







    /**
     * Returns routes
     *
     * @return RouteInterface[]
    */
    public function getRoutes(): array;
}
