<?php

declare(strict_types=1);

namespace Laventure\Component\Routing;

use Laventure\Component\Routing\Collection\RouteCollection;
use Laventure\Component\Routing\Collection\RouteCollectionInterface;
use Laventure\Component\Routing\Enums\HttpMethod;
use Laventure\Component\Routing\Route\RouteFactory;
use Laventure\Component\Routing\Route\RouteFactoryInterface;
use Laventure\Component\Routing\Route\RouteInterface;

/**
 * Router
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package  Laventure\Component\Routing
 *
 * Generated By PHPStorm 20.12.2023
 */
class Router implements RouterInterface
{
    /**
     * @var RouteCollectionInterface
    */
    protected RouteCollectionInterface $collection;


    /**
     * @var RouteFactory
    */
    protected RouteFactory $routeFactory;




    /**
     * @param RouteCollectionInterface|null $collection
     *
     * @param RouteFactoryInterface|null $routeFactory
    */
    public function __construct(
        RouteCollectionInterface $collection = null,
        RouteFactoryInterface $routeFactory = null
    ) {
        $this->collection   = $collection ?: new RouteCollection();
        $this->routeFactory = $routeFactory ?: new RouteFactory();
    }



    /**
     * @param RouteInterface $route
     *
     * @return RouteInterface
    */
    public function addRoute(RouteInterface $route): RouteInterface
    {
        return $this->collection->addRoute($route);
    }



    /**
     * @param string $name
     *
     * @param RouteInterface $route
     *
     * @return RouteInterface
    */
    public function add(string $name, RouteInterface $route): RouteInterface
    {
        return $this->collection->add($name, $route);
    }





    /**
     * @param string $methods
     *
     * @param string $path
     *
     * @param mixed $action
     *
     * @param string|null $name
     *
     * @return RouteInterface
    */
    public function makeRoute(string $methods, string $path, mixed $action, string $name = null): RouteInterface
    {
        return $this->routeFactory->createRouteFromStringMethods($methods, $path, $action, $name);
    }





    /**
     * @inheritDoc
    */
    public function map(string $methods, string $path, mixed $action, string $name = null): RouteInterface
    {
        $route = $this->makeRoute($methods, $path, $action, $name);

        if ($name) {
            return $this->add($name, $route);
        }

        return $this->addRoute($route);
    }




    /**
     * @inheritDoc
    */
    public function get(string $path, mixed $action, string $name = null): RouteInterface
    {
        return $this->map(HttpMethod::GET, $path, $action, $name);
    }






    /**
     * @inheritDoc
    */
    public function post(string $path, mixed $action, string $name = null): RouteInterface
    {
        return $this->map(HttpMethod::POST, $path, $action, $name);
    }




    /**
     * @inheritDoc
    */
    public function put(string $path, mixed $action, string $name = null): RouteInterface
    {
        return $this->map(HttpMethod::PUT, $path, $action, $name);
    }




    /**
     * @inheritDoc
    */
    public function delete(string $path, mixed $action, string $name = null): RouteInterface
    {
        return $this->map(HttpMethod::DELETE, $path, $action, $name);
    }





    /**
     * @inheritDoc
    */
    public function match(string $method, string $path): RouteInterface|false
    {
        foreach ($this->getRoutes() as $route) {
            if ($route->match($method, $path)) {
                return $route;
            }
        }

        return false;
    }





    /**
     * @inheritDoc
    */
    public function generate(string $name, array $parameters = []): ?string
    {
        if (!$this->collection->hasRoute($name)) {
            return null;
        }

        return $this->collection->getRoute($name)->generate($parameters);
    }




    /**
     * @inheritDoc
    */
    public function getRoutes(): array
    {
        return $this->collection->getRoutes();
    }




    /**
     * @return RouteCollectionInterface
    */
    public function getCollection(): RouteCollectionInterface
    {
        return $this->collection;
    }
}
