<?php

declare(strict_types=1);

namespace Laventure\Component\Routing\Collection;

use Laventure\Component\Routing\Route\RouteInterface;

/**
 * RouteCollectionInterface
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package  Laventure\Component\Routing\Collection
 *
 * Generated By PHPStorm 20.12.2023
*/
interface RouteCollectionInterface
{
    /**
     * @param RouteInterface $route
     *
     * @return RouteInterface
    */
    public function addRoute(RouteInterface $route): RouteInterface;



    /**
     * @param string $name
     *
     * @param RouteInterface $route
     *
     * @return RouteInterface
    */
    public function add(string $name, RouteInterface $route): RouteInterface;




    /**
     * Returns route collections
     *
     * @return RouteInterface[]
    */
    public function getRoutes(): array;





    /**
     * Determine if exists named route
     *
     * @param string $name
     *
     * @return bool
    */
    public function hasRoute(string $name): bool;





    /**
     * Returns route by given name
     *
     * @param string $name
     *
     * @return RouteInterface|null
    */
    public function getRoute(string $name): ?RouteInterface;




    /**
     * Returns named routes
     *
     * @return RouteInterface[]
    */
    public function getNamedRoutes(): array;
}
