<?php
declare(strict_types=1);

namespace Laventure\Component\Routing\Middlewares;

/**
 * AuthenticatedMiddleware
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package  Laventure\Component\Routing\Middlewares
 *
 * Generated By PHPStorm 20.12.2023
 */
class AuthenticatedMiddleware
{
        public function __invoke($request, callable $next)
        {
            // TODO: Implement __invoke() method.
        }
}