<?php

declare(strict_types=1);

namespace Laventure\Component\Routing\Route;

/**
 * RouteFactory
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package  Laventure\Component\Routing\Route
 *
 * Generated By PHPStorm 20.12.2023
 */
class RouteFactory
{
    /**
     * @param array|string $methods
     * @param string $path
     * @param mixed $action
     * @param string|null $name
     * @return Route
    */
    public function make(
        array|string $methods,
        string $path,
        mixed  $action,
        ?string $name = null
    ): Route {
        return new Route($methods, $path, $action, $name);
    }
}
