<?php

declare(strict_types=1);

namespace Laventure\Component\Routing\Route;

/**
 * RouteFactoryInterface
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package  Laventure\Component\Routing\Route
 *
 * Generated By PHPStorm 20.12.2023
 */
interface RouteFactoryInterface
{
    /**
     * @param array $methods
     *
     * @param string $path
     *
     * @param mixed $action
     *
     * @param string|null $name
     *
     * @return RouteInterface
    */
    public function createRoute(
        array $methods,
        string $path,
        mixed  $action,
        ?string $name = null
    ): RouteInterface;




    /**
     * @param string $methods
     *
     * @param string $path
     *
     * @param mixed $action
     *
     * @param string|null $name
     *
     * @return RouteInterface
    */
    public function createRouteFromStringMethods(
        string $methods,
        string $path,
        mixed  $action,
        ?string $name = null
    ): RouteInterface;
}
