<?php
declare(strict_types=1);

namespace Laventure\Component\Routing\Route;

/**
 * RouteInterface
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package Laventure\Component\Routing\Route
 *
 * Generated By PHPStorm 20.12.2023
 */
interface RouteInterface extends \ArrayAccess
{
    /**
     * Returns route methods
     *
     * @return array
    */
    public function getMethods(): array;



    /**
     * Returns route path
     *
     * @return string
    */
    public function getPath(): string;





    /**
     * Returns route action will be executed.
     *
     * @return mixed
    */
    public function getAction(): mixed;





    /**
     * Returns matches params from url
     *
     * @return array
    */
    public function getParams(): array;





    /**
     * Returns name of route
     *
     * @return string|null
    */
    public function getName(): ?string;





    /**
     * Returns route middlewares
     *
     * @return array
    */
    public function getMiddlewares(): array;




    /**
     * Returns route requirements rules
     *
     * @return array
    */
    public function getPatterns(): array;





    /**
     * Returns route options
     *
     * @return array
    */
    public function getOptions(): array;







    /**
     * @param string $method
     *
     * @param string $path
     *
     * @return bool
    */
    public function match(string $method, string $path): bool;






    /**
     * Generate route path
     *
     * @param array $parameters
     *
     * @return string
    */
    public function generate(array $parameters = []): string;
}
