<?php

declare(strict_types=1);

namespace Laventure\Component\Routing\Route;

/**
 * RouteFactory
 *
 * @author Jean-Claude <jeanyao@ymail.com>
 *
 * @license https://github.com/jeandev84/laventure-framework/blob/master/LICENSE
 *
 * @package  Laventure\Component\Routing\Route
 *
 * Generated By PHPStorm 20.12.2023
 */
class RouteFactory implements RouteFactoryInterface
{
    /**
     * @inheritdoc
    */
    public function createRoute(
        array $methods,
        string $path,
        mixed  $action,
        ?string $name = null
    ): RouteInterface {

        return new Route($methods, $path, $action, $name);
    }


    /**
     * @inheritdoc
    */
    public function createRouteFromStringMethods(
        string $methods,
        string $path,
        mixed $action,
        ?string $name = null
    ): RouteInterface {
        return $this->createRoute(
            explode('|', $methods),
            $path,
            $action,
            $name
        );
    }
}
